# Generated by Django 4.1.1 on 2022-09-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reedpiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('length', models.FloatField()),
                ('diam', models.FloatField()),
                ('thickness', models.FloatField()),
                ('roundness', models.FloatField()),
            ],
        ),
    ]
